# Generated by Django 4.2.4 on 2023-08-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
