# Generated by Django 4.2.4 on 2023-08-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0003_userpost_created_at_alter_userpost_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='username',
            new_name='user',
        ),
    ]
